# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHKSXZ4rmecbZj51eH4_jwr5Gl4dvSb-
"""

import pandas as pd
df = pd.read_csv("data.csv")

for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.loc[x, "Duration"] = 100
for x in df.index:
  if df.loc[x, "Calories"] < 500:
    df.loc[x, "Calories"] = 510
for x in df.index:
  av = (df.loc[x, "Pulse"] + df.loc[x, "Maxpulse"])/2
  df.loc[x, "Average Pulse"] = av

import matplotlib.pyplot as plt
df.plot(kind = 'box', x = 'Duration', y = 'Calories')
plt.show()