# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXvwoZ0N12i6Ed08NaoTpTbUIg5XaDwj
"""

import pandas as pd
df = pd.read_csv("data01.csv")

#problem 1
median_house_value = df['median_house_value'].median
print(median_house_value)

#problem 2
median_total_rooms = df['total_rooms'].median
for x in df.index:
  if df.loc[x, "total_rooms"] < 500:
    df.loc[x, "total_rooms"] = median_total_rooms

#problem 3
for x in df.index:
  if df.loc[x, "housing_median_age"] < 25:
    #print(df.loc[x])
    print("-----------------------------")
    print("longitude:", df.loc[x, "longitude"])
    print("latitude:", df.loc[x, "latitude"])
    print("housing_median_age:", df.loc[x, "housing_median_age"])
    print("total_rooms:", df.loc[x, "total_rooms"])
    print("total_bedrooms:", df.loc[x, "total_bedrooms"])
    print("population:", df.loc[x, "population"])
    print("households:", df.loc[x, "households"])
    print("median_income:", df.loc[x, "median_income"])
    print("median_house_value:", df.loc[x, "median_house_value"])

#problem 4
import matplotlib.pyplot as plt
df.plot(kind = 'scatter', x = 'housing_median_age', y = 'median_house_value')
plt.show()